---
title: "README"
output: html_document
---

Дані, з якими ми працюємо, представляють дані, зібрані з акселерометрів зі смартфона Samsung Galaxy S. Повний опис доступний на сайті, де були отримані дані: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartph ones

Дані для лабораторної роботи містяться за посиланням:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20 Dataset.zip

Даний код реалізовує:
 - Зчитування даних з різних файлів
 - Обʼєднання даних в одну таблицю
 - Видалення дублікатів
 А також виконує наступні дії:
 
2. Витягує лише вимірювання середнього значення та стандартного
відхилення (mean and standard deviation) для кожного вимірювання.
3. Використовує описові назви діяльностей (activity) для найменування
діяльностей у наборі даних.
4. Відповідноприсвоюєзміннимунаборіданихописовіімена.
5. З набору даних з кроку 4 створити другий незалежний акуратний набір
даних (tidy dataset) із середнім значенням для кожної змінної для кожної діяльності та кожного суб’єкту (subject).